"2023-01":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip: 10
      peak: 20
      flat: 30
      valley: 40
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 13.05
      peak: 22.94
      flat: 37.34
      valley: 26.67
  T8:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 24.77
      peak: 19.95
      flat: 32.3
      valley: 22.98
  T9:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 21.88
      peak: 13.27
      flat: 36.47
      valley: 28.38
"2023-02":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip: 19.07
      peak: 27.1
      flat: 19.99
      valley: 33.84
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T7:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 37.5
      peak: 62.5
      flat: 0
      valley: 0
  T8:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 0
      peak: 0
      flat: 24.06
      valley: 75.94
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-03":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-04":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 62.5
      flat: 37.5
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 35.1
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-05":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 62.5
      flat: 37.5
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 35.1
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-06":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: True
    ratio:
      tip: 37.5
      peak: 62.5
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-07":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: True
    ratio:
      tip: 37.5
      peak: 62.5
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-08":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: True
    ratio:
      tip: 37.5
      peak: 62.5
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-09":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 62.5
      flat: 37.5
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 35.1
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-10":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 62.5
      flat: 37.5
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 35.1
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-11":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 62.5
      flat: 37.5
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip:
      peak: 35.1
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
"2023-12":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: True
    ratio:
      tip: 37.5
      peak: 62.5
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: True
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:




















































