"2023-01":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip: 25
      peak: 75
      flat: 0
      valley: 0
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 11.6
      peak: 25.6
      flat: 33
      valley: 29.8
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 11.6
      peak: 25.6
      flat: 33
      valley: 29.8
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 11.6
      peak: 25.6
      flat: 33
      valley: 29.8
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 11.6
      peak: 25.6
      flat: 33
      valley: 29.8

"2023-02":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip: 25
      peak: 75
      flat: 0
      valley: 0
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 12
      peak: 20.4
      flat: 34.3
      valley: 33.3
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 12
      peak: 20.4
      flat: 34.3
      valley: 33.3
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 12
      peak: 20.4
      flat: 34.3
      valley: 33.3
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 12
      peak: 20.4
      flat: 34.3
      valley: 33.3

"2023-12":
  T1:
    time:
      - 17:00-19:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 16:00-17:00
      - 19:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:


"2023-03":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 32.7
      flat: 35
      valley: 32.3
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 32.7
      flat: 35
      valley: 32.3
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 32.7
      flat: 35
      valley: 32.3
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 32.7
      flat: 35
      valley: 32.3



"2023-04":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 34.1
      flat: 33.6
      valley: 32.3
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 34.1
      flat: 33.6
      valley: 32.3
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 34.1
      flat: 33.6
      valley: 32.3
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 34.1
      flat: 33.6
      valley: 32.3



"2023-05":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 36.1
      flat: 33.6
      valley: 30.3
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 36.1
      flat: 33.6
      valley: 30.3
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 36.1
      flat: 33.6
      valley: 30.3
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 36.1
      flat: 33.6
      valley: 30.3


"2023-09":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 35.4
      flat: 32.5
      valley: 32.1
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 35.4
      flat: 32.5
      valley: 32.1
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 35.4
      flat: 32.5
      valley: 32.1
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 0
      peak: 35.4
      flat: 32.5
      valley: 32.1


"2023-10":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:


"2023-11":
  T3:
    time:
      - 00:00-01:00
      - 06:00-12:00
      - 15:00-16:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 01:00-06:00
      - 12:00-15:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 16:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:


"2023-06":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: False
    ratio:
      tip: 37.5
      peak: 62.5
      flat: 0
      valley: 0
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.8
      peak: 20.5
      flat: 33.5
      valley: 31.2
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.8
      peak: 20.5
      flat: 33.5
      valley: 31.2
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.8
      peak: 20.5
      flat: 33.5
      valley: 31.2
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.8
      peak: 20.5
      flat: 33.5
      valley: 31.2


"2023-07":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: False
    ratio:
      tip: 37.5
      peak: 62.5
      flat: 0
      valley: 0
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 14.6
      peak: 20.5
      flat: 33.5
      valley: 31.4

"2023-08":
  T1:
    time:
      - 19:00-22:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T2:
    time:
      - 15:00-19:00
      - 22:00-23:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T3:
    time:
      - 08:00-15:00
      - 23:00-24:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T4:
    time:
      - 00:00-08:00
    haveRatio: False
    ratio:
      tip:
      peak:
      flat:
      valley:
  T5:
    time:
      - 15:00-23:00
    haveRatio: False
    ratio:
      tip: 37.5
      peak: 62.5
      flat: 0
      valley: 0
  T6:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 15.5
      peak: 21.5
      flat: 33.7
      valley: 29.3
  T7:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 15.5
      peak: 21.5
      flat: 33.7
      valley: 29.3
  T8:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 15.5
      peak: 21.5
      flat: 33.7
      valley: 29.3
  T9:
    time:
      - 00:00-24:00
    haveRatio: False
    ratio:
      tip: 15.5
      peak: 21.5
      flat: 33.7
      valley: 29.3

































